Repository redBorder/cookbook-minio, pull requests merged in 2024-05, with the labels that each got.

#6 Update README
  README.md
Labels: enhancement, size/S, kind/documentation

#8 Fix: master -> development
  README.md
Labels: size/S, kind/bug

#7 Improvement/fix cookbook lint
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/configure_solo.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: enhancement, size/M, lint, refactor, kind/bug

#9 Release 0.0.5
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/configure_solo.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: kind/documentation, size/L

#22 Update README.md
  README.md
Labels: size/S, kind/documentation

#23 Update README.md
  README.md
Labels: size/M, kind/documentation
