Repository redBorder/cookbook-minio, pull requests merged in 2024-04, with the labels that each got.

#4 Added ../rpm.yml to .github/workflows/
  .github/workflows/rpm.yml
Labels: kind/feature, size/M

#3 add ipaddress sync
  resources/providers/config.rb
  resources/resources/config.rb
Labels: kind/feature, size/XS

#5 Release 0.0.4
  CHANGELOG.md
  resources/metadata.rb
  resources/providers/config.rb
  resources/resources/config.rb
Labels: size/S, kind/documentation
